bcgov/SDPR_Case_Management_SuiteCRM

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/containers/list-filter/list-filter.component.html
removing quick filter section as a part of filter button styling
=> feat: removed orange quick filter box

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/abstracts/_variables.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_dropdown.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar.scss
=> feat: recolour navbar

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/abstracts/_variables.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_button.scss, docker/advocase-image/build-files/suitecrm/public/legacy/themes/suite8/css/Dawn/variables.scss
Issues:
- Spacing doesn't look exactly correct but it's close
- Filter funnel icon currently not being using so it's temporarily a upside down triangle
=> feat: filter button styling

helm/suitecrm/templates/cron-job.yaml
=> Cron schedule reference

docker/advocase-image/scripts/cron.sh, helm/suitecrm/templates/cron-job.yaml
- Cron script replacing right string
- Indentation levels
- Schedule piping to quote function
=> SuiteCRM cron job

helm/suitecrm/templates/cron-job.yaml
- Cron job container image pull policy
=> Cron job container image pull policy

docker/advocase-image/scripts/liveness-healt-check.sh, helm/suitecrm/templates/network-policy.yaml
=> Liveness check script

docker/advocase-image/Dockerfile, docker/advocase-image/scripts/liveness-healt-check.sh, docker/advocase-image/scripts/readiness-health-check.sh
- Renamed `liveness-healt-check.sh` to `readiness-health-check.sh`
=> Scripts renamed

docker/advocase-image/scripts/readiness-health-check.sh, docker/advocase-image/scripts/startup-health-check.sh, helm/suitecrm/templates/deployment.yaml
=> Script fixes

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_dropdown.scss, docker/advocase-image/build-files/suitecrm/public/legacy/themes/suite8/css/Dawn/color-palette.scss
Added dropdown component file and changed text colour of main nav dropdown.
=> fix: nav dropdown text colour

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/base-navbar/base-navbar.component.html, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/abstracts/_variables.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_svg-mobile.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar-mobile.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar.scss, docker/advocase-image/build-files/suitecrm/public/legacy/themes/suite8/css/Dawn/color-palette.scss
1. Recolour mobile nav
2. New styling for nav quick create button
=> feat: recolour mobile navbar and create custom styling for create button

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/field-layout/field-layout.component.html, docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/record-content-skeleton/record-content-skeleton.component.html, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_field-layout.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_tabs.scss
Focuses on styling "Case Overview" panel in the case details view. Not 100% complete as there are issues with padding that I am currently working on.
=> feat: styling case overview panel in details view

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/base-navbar/base-navbar.component.html, docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/home-menu-item/base-home-menu-item.component.html, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/abstracts/_variables.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_searchbar.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar.scss, docker/advocase-image/build-files/suitecrm/public/legacy/themes/suite8/css/Dawn/color-palette.scss
1. Remove action history button from nav
2. Style quick create button
3. Style home nav link
4. Style nav search bar
=> styled nav create button and home link

helm/suitecrm/templates/deployment.yaml
- Liveness probe using `tcpSocket`
- Readiness and start up probes using `httpGet`
=> Changes in liveness, readiness, and start up probes

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/abstracts/_variables.scss, docker/advocase-image/build-files/suitecrm/core/shell/src/themes/suite8/css/components/_widget-bar.scss, docker/advocase-image/build-files/suitecrm/public/legacy/themes/suite8/css/Dawn/variables.scss
Issues:
- text/content inside the bar not aligned to the left (on local) and currently working on fixing it
- hazard icon used temporarily instead of font awesome info icon
=> feat: added styling to alert widget bar

.gitignore, docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/menu-item-link/base-menu-item-link.component.html, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_dropdown.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar-mobile.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar.scss
Styling nav items and main nav submenu
=> Feat/colour nav/lb

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_button.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_dropdown.scss
Removes "funnel" icon which got applied to all buttons
Fixed colour issues in bulk action dropdown which was unreadable
=> fix: removed icon from button and colours

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_field-layout.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_tabs.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_panel.scss
Changing top panel for each subpanel to be correct colour and fonts to BC Sans
Also slight spacing changes for Overview panel in details view
=> fix: colours and label spacing fonts

docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_dropdown.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_notifications.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_searchbar.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_svg.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar-mobile.scss
1. Updated nav item highlight to reflect new design specifications
2. Fix nav action items dropdown styling
3. Search bar border
=> feat: update nav item highlight styling and action item dropdown

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/sub-menu-recently-viewed/base-sub-menu-recently-viewed.component.html, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_dropdown.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar-mobile.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_navbar.scss
1. Fixed colour of "recently viewed" submenu item and removed icon
2. Fixed QA items (padding, margin, font weight, font size)
=> fix: recently viewed styling and navbar spacing

helm/suitecrm/templates/app-cron-job.yaml, helm/suitecrm/templates/s3-file-backup-cron-job.yaml, helm/suitecrm/values.yaml, openshift/README.md, openshift/s3-backup-secrets.yaml
- Added cron job to backup files from `/suitecrm/public/legacy/upload` to a S3 bucket
- Created new `./openshift/s3-backup-secrets.yaml` file to setup S3 bucket AWS credentials
=> S3 bucket backup cron

docker/advocase-image/build-files/suitecrm/public/legacy/custom/Extension/modules/Contacts/Ext/Language/_override_en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/custom/Extension/modules/Documents/Ext/Language/_override_en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/custom/include/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Cases/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Cases/metadata/subpanels/Contact_subpanel_cases.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Cases/metadata/subpanels/default.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/metadata/editviewdefs.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/metadata/listviewdefs.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/metadata/subpanels/Case_subpanel_contacts.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/metadata/subpanels/Contact_subpanel_Contacts.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Contacts/metadata/subpanels/Contact_subpanel_contacts.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Documents/Ext/Language/en_us.lang.ext.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Documents/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Documents/metadata/subpanels/Case_subpanel_documents.php, docker/advocase-image/build-files/suitecrm/public/legacy/modules/Documents/metadata/subpanels/Contact_subpanel_documents.php
This reverts commit ed370fb8a776e7a085506c9baa9bee94649bbbdc.
=> Revert "Revert "Feat/asa-233: contant subpanel Tables""

.github/workflows/main-deploy.yaml, .github/workflows/reusable-build-dockerfile.yaml
- Added reusable docker image build pipeline
- Added main deploy file
=> ASA-228: feat: BC GOV SuiteCRM build pipeline

.github/workflows/main-deploy.yaml, .github/workflows/reusable-build-dockerfile.yaml
- Pull from artfactory condition in case of building Advocase image
=> ASA-228 feat: Pull from artfactory condition

.github/workflows/reusable-build-dockerfile.yaml
=> ASA-228 fix: registry path

.github/workflows/reusable-build-dockerfile.yaml
=> ASA-228 fix: remove pull conditional

.github/workflows/suitecrm-push-to-artifactory.yaml
- Added options for SuiteCRM build workflow
=> ASA-228 feat: Added options for SuiteCRM build workflow

.github/workflows/reusable-build-dockerfile.yaml, .github/workflows/suitecrm-push-to-artifactory.yaml
- Added default option
-  fix: error referencing a variable
=> Asa 228/bc gov suitecrm pipeline/rs

tests/cypress/e2e/Accessibility/Communication/comm.cy.ts, tests/cypress/e2e/Accessibility/Communication/comm.feature, tests/cypress/e2e/Communication/comm.cy.ts, tests/cypress/e2e/Communication/comm.feature, tests/cypress/e2e/Contact/contact.cy.ts, tests/cypress/e2e/Contact/contact.feature
Automate Testing for Communication Module, Accessibility of Communication Module.
=> Automate Testing

docker/advocase-image/build-files/suitecrm/public/legacy/custom/modules/Contacts/metadata/detailviewdefs.php
- Detail view `first_name` field definition
=> ASA-260 fix: detailview `first_name` field definition

docker/suitecrm-image/suitecrm/scripts/suitecrm/php/rebuild-suitecrm.php
- Added repair js files to rebuild and repair PHP command
=> feat: repair js files command

docker/advocase-image/build-files/suitecrm/public/legacy/custom/include/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/custom/modules/Meetings/language/en_us.lang.php, docker/advocase-image/build-files/suitecrm/public/legacy/custom/modules/Meetings/metadata/editviewdefs.php
Reverts bcgov/SDPR_Case_Management_SuiteCRM#279
=> Revert "feat/update label text in create communication"

.github/workflows/advocase-pr-merge-deployment.yaml, .github/workflows/reusable-wait-for-rollout.yaml, openshift/aps-network-policy.yaml
=> Asa 184/owasp zap integration/rs

tests/cypress/e2e/Contact/contact.cy.ts, tests/cypress/e2e/Contact/contact.feature
full contact automate test file with description file
=> contact.cy.ts and contact.feature

tests/cypress/e2e/Accessibility/Contact/contact.cy.ts, tests/cypress/e2e/Accessibility/Contact/contact.feature
Accessibility Test for Contact Module
=> contact.cy.ts and contact.feature of accessibility test

tests/cypress/e2e/Accessibility/Case/case.cy.ts, tests/cypress/e2e/Accessibility/Case/case.feature
Case Module accessibility automate test
=> case.cy.ts and case.feature for case module accessibility test

tests/cypress/e2e/Case/case.cy.ts, tests/cypress/e2e/Case/case.feature
Case module automate test and test features.
=> case.cy.ts and case.feature

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/panel/panel.component.html
Reverts bcgov/SDPR_Case_Management_SuiteCRM#447
=> Revert "fix: capitalize overview subpanel headers"

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/minimise-button/minimise-button.component.html, docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/minimise-button/minimise-button.component.ts, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/components/_action-group-menu.scss, docker/advocase-image/build-files/suitecrm/core/app/shell/src/themes/suite8/css/layout/_panel.scss
=> asa-205/fix: change minimise icon when overview panel is collapsed

docker/suitecrm-image/suitecrm/build-files/suitecrm/public/legacy/include/utils.php, docker/suitecrm-image/suitecrm/scripts/suitecrm/download.sh
=> Patching - SuiteCRM v8.6.2

docker/advocase-image/build-files/suitecrm/core/app/core/src/lib/components/navbar/base-navbar/base-navbar.component.ts
=> Patch SuiteCRM v8.6.2

docker/suitecrm-image/suitecrm/scripts/suitecrm/download.sh
Reverts bcgov/SDPR_Case_Management_SuiteCRM#563
=> Revert "chore: patch to version 8.7.1"
